model:
  pretrained: doclayout_yolo_docstructbench_imgsz1024.pt
  num_classes: 15
  input_size: 1024
  device: cuda
  # Layer freezing configuration
  freeze_backbone: true  # Keep backbone frozen during both phases
  freeze_neck: true      # Will be unfrozen after phase 1 (epoch 20)
  # Learning rate multipliers for different parts of the model
  lr_multipliers:
    backbone: 0.1     # Lower learning rate for backbone if unfrozen
    neck: 1.0         # Full learning rate for neck
    head: 1.0         # Full learning rate for head
  class_names:
    0: "text"
    1: "title"
    2: "figure"
    3: "table"
    4: "list"
    5: "header"
    6: "footer"
    7: "caption"
    8: "formula"
    9: "page_number"
    # Add more classes as needed

training:
  epochs: 50
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.0005
  num_workers: 4
  save_interval: 5
  output_dir: checkpoints
  early_stopping_patience: 10
  min_lr: 1e-6
  warmup_epochs: 3

data:
  train_dir: data/train  # Update to point to the train directory
  val_dir: data/val
  image_size: 1024
  augmentation:
    # Geometric transforms
    horizontal_flip: 0.5
    vertical_flip: 0.3
    rotate: 10  # degrees
    scale: [0.8, 1.2]
    translate: 0.1  # 10% of image size
    shear: 5  # degrees
    
    # Color transforms
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0.02
    
    # Advanced augmentations
    cutout: 0.1  # probability
    cutout_holes: 3
    cutout_size: [0.1, 0.3]  # fraction of image size
    
    # Normalization
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
